name = "geo"
type = "javascript"
compatibility_date = "2021-10-25"

[env.staging]
name = "staging-geo"
vars = { ENVIRONMENT = "staging" }
workers_dev = true

[env.prod]
name = "prod-geo"
vars = { ENVIRONMENT = "production" }
route = "*erfianugrah.com/geo"